### ISSUE TITLE
Request: Testing Examples?

### ISSUE THREAD

**Issue by jasonmacdonald** [prisma/prisma-client-extensions#11]
I've been struggling to try to properly mock and test a sharable extension, especially when it uses `query` with `$allModels` and `$allOperations`. A more complex example that wraps an existing method, like `update` on all models would be very helpful as most of the examples seem to assume a new property. I'm constantly running into Typescript typing errors.

**Comment by ruheni** [comment]
👋 @jasonmacdonald 

Apologies for not responding sooner. While this is not covered in the example, you can use the Read Replica extension we built as a reference for testing. 🙂

**Comment by meleyal** [comment]
https://github.com/prisma/extension-read-replicas
