### ISSUE TITLE
Type issues in example callback-free-itx with Prisma v5

### ISSUE THREAD

**Issue by MarcErdmann** [prisma/prisma-client-extensions#27]
The example "callback-free-itx" has type issues with Prisma v5. The function parameter txClient: Prisma.TransactionClient results in a type mismatch.
Can you update the example to use Prisma v5?

**Comment by ruheni** [comment]
👋 Marc

We're currently looking into it and will update the examples very soon!

**Comment by ruheni** [comment]
Quick update: We've updated the types for the example and it should be functional. Let us know if you may have any further issues or questions
