### ISSUE TITLE
Callback-free-itx does not perform a rollback if rollback method is called

### ISSUE THREAD

**Issue by andreasvh-conceto** [prisma/prisma-client-extensions#3]
Hello,

i tried out the callback-free-itx client extension example. The rollback seems not to work. Code for reproducing this issue is here:
https://github.com/prisma/prisma/discussions/17769#discussioncomment-4952111

Would be thankful for a fix.

Best regards
Andreas

**Comment by ruheni** [comment]
Apologies for the late response. The example has been updated with the suggestion in this issue comment: https://github.com/prisma/prisma-client-extensions/issues/12#issuecomment-1499748837
